" vim req
set nocompatible

" you want emojis right?
set encoding=utf-8

" yank to clipboard on linux
set clipboard=unnamedplus

if has("unix")
  let s:uname = system("uname")
  if s:uname == "Darwin\n"
    " vodoo for true color, along with .tmux.conf settings
    " https://tomlankhorst.nl/iterm-tmux-vim-true-color/
    set termguicolors
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    set clipboard=unnamed
  endif
endif

" windows/wsl yank support
let s:clip = '/mnt/c/Windows/System32/clip.exe'  " change this path
if executable(s:clip)
  augroup WSLYank
    autocmd!
    autocmd TextYankPost * if v:event.operator ==# 'y' | call system(s:clip, @0) | endif
  augroup END
endif

" :e automplete in subdirectories
set path+=**
set wildmenu

" ignore bullshit directories for ctrlp plugin
let g:ctrlp_custom_ignore = '\.git\|node_modules'

" allow project/directory specific .vimrc
set exrc
set secure

filetype plugin indent on

call plug#begin()
Plug 'prettier/vim-prettier', { 'do': 'npm install' }
Plug 'pangloss/vim-javascript'
Plug 'leafgarland/typescript-vim'
Plug 'mxw/vim-jsx'
Plug 'dracula/vim', {'as': 'dracula'}
Plug 'vim-airline/vim-airline'
Plug 'airblade/vim-gitgutter'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'rhysd/vim-clang-format'
Plug 'tpope/vim-dispatch'
call plug#end()

colorscheme dracula

" terminals that don't support italics (a lot of them) get tripped up
" and have an ugly background color instead of italics
let g:dracula_italic = 0

" new version of vim is dumb and wont delete over line breaks
set backspace=2

" enable syntax highlight
syntax enable

set autoindent
set smartindent
set ttyfast

" spaces to tabs
set expandtab
set tabstop=2
set shiftwidth=2

" turn on search highlighting
set hlsearch

" deal with upper/lower better
set smartcase
set ignorecase

" Light 80 column ruler for non-intrusive visual guide for format
if exists('+colorcolumn')
   set colorcolumn=80
endif

" Add line numbers
set number

" i hate comment continuation with a passion
autocmd BufNewFile,BufRead * setlocal formatoptions-=cro
