" vim req
set nocompatible

" you want emojis right?
set encoding=utf-8

" yank to clipboard on linux
set clipboard=unnamedplus

if has("unix")
  let s:uname = system("uname")
  if s:uname == "Darwin\n"
    " vodoo for true color, along with .tmux.conf settings
    " https://tomlankhorst.nl/iterm-tmux-vim-true-color/
    set termguicolors
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    set clipboard=unnamed
  endif
endif


" windows/wsl yank support
let s:clip = '/mnt/c/Windows/System32/clip.exe'  " change this path
if executable(s:clip)
  augroup WSLYank
    autocmd!
    autocmd TextYankPost * if v:event.operator ==# 'y' | call system(s:clip, @0) | endif
  augroup END
endif

" :e automplete in subdirectories
set path+=**
set wildmenu

" ignore bullshit directories for ctrlp plugin
let g:ctrlp_custom_ignore = '\.git\|node_modules'

" allow project/directory specific .vimrc
set exrc
set secure

filetype plugin indent on

call plug#begin()
Plug 'prettier/vim-prettier', { 'do': 'npm install' }
Plug 'othree/yajs'
Plug 'mxw/vim-jsx'
Plug 'hashivim/vim-terraform'
Plug 'dracula/vim', {'as': 'dracula'}
Plug 'vim-airline/vim-airline'
Plug 'airblade/vim-gitgutter'
Plug 'pearofducks/ansible-vim', { 'do': 'cd ./UltiSnips; ./generate.py' }
Plug 'mustache/vim-mustache-handlebars'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'rhysd/vim-clang-format'
Plug 'tpope/vim-dispatch'
call plug#end()

colorscheme dracula

" https://superuser.com/questions/457911/in-vim-background-color-changes-on-scrolling/588243
" set t_ut=

let g:prettier#autoformat = 0
au BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml Prettier
au BufRead,BufNewFile *.js setlocal syntax=javascript.jsx
au BufRead,BufNewFile *.yaml,*.yml set filetype=yaml.ansible

" automatically wrap in markdown
au BufRead,BufNewFile *.md setlocal textwidth=80

" new version of vim is dumb and wont delete over line breaks
set backspace=2

" enable syntax highlight
syntax enable

set autoindent
set smartindent
set ttyfast

" spaces to tabs
set expandtab
set tabstop=2
set shiftwidth=2

" turn on search highlighting
set hlsearch

" deal with upper/lower better
set smartcase
set ignorecase

" Light 80 column ruler for non-intrusive visual guide for format
if exists('+colorcolumn')
   set colorcolumn=80
endif

" Add line numbers
set number

" Set the status line to something nifty
set stl=%f\ Line:%l/%L\ (%p%%)\ Col:%v\ Buf:#%n\ 0x%B

" always show a status line
set laststatus=2
